name: "Lint, test and coverage of Python code"

inputs:
  skip-tests:
    description: "Flag that indicates whether tests should be skipped"
    default: false
    type: boolean
  main-module:
    description: "Main python module of your python project"
    default: "src"
  codecov-token:
    description: "Codecov upload token"
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Ruff lint check"
      run: uv run ruff check ${{ inputs.main-module }}
      shell: bash
    - name: "Ruff format check"
      run: uv run ruff format ${{ inputs.main-module }} --check
      shell: bash
    - name: "Mypy check"
      run: uv run mypy ${{ inputs.main-module }}
      shell: bash
    - name: "Test using pytest"
      if: ${{ !inputs.skip-tests }}
      run: uv run pytest --cov=${{ inputs.main-module }} --cov-report=json --cov-report=term
      env:
        PYTHONPATH: .
      shell: bash
    - uses: codecov/codecov-action@v5
      if: ${{ !inputs.skip-tests && inputs.codecov-token != '' }}
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
